// Code generated by MockGen. DO NOT EDIT.
// Source: service/diagnoses/diagnosis_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/diagnoses/diagnosis_repo.go -destination=service/diagnoses/mock_repo.go -package=diagnoses
//

// Package diagnoses is a generated GoMock package.
package diagnoses

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDiagnoseRepo is a mock of DiagnoseRepo interface.
type MockDiagnoseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDiagnoseRepoMockRecorder
	isgomock struct{}
}

// MockDiagnoseRepoMockRecorder is the mock recorder for MockDiagnoseRepo.
type MockDiagnoseRepoMockRecorder struct {
	mock *MockDiagnoseRepo
}

// NewMockDiagnoseRepo creates a new mock instance.
func NewMockDiagnoseRepo(ctrl *gomock.Controller) *MockDiagnoseRepo {
	mock := &MockDiagnoseRepo{ctrl: ctrl}
	mock.recorder = &MockDiagnoseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiagnoseRepo) EXPECT() *MockDiagnoseRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiagnoseRepo) Create(diagnose *Diagnose) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", diagnose)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDiagnoseRepoMockRecorder) Create(diagnose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiagnoseRepo)(nil).Create), diagnose)
}

// GetByAppointmentID mocks base method.
func (m *MockDiagnoseRepo) GetByAppointmentID(appointmentID int64) (*Diagnose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAppointmentID", appointmentID)
	ret0, _ := ret[0].(*Diagnose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAppointmentID indicates an expected call of GetByAppointmentID.
func (mr *MockDiagnoseRepoMockRecorder) GetByAppointmentID(appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAppointmentID", reflect.TypeOf((*MockDiagnoseRepo)(nil).GetByAppointmentID), appointmentID)
}

// GetByID mocks base method.
func (m *MockDiagnoseRepo) GetByID(id int64) (*Diagnose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*Diagnose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDiagnoseRepoMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDiagnoseRepo)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockDiagnoseRepo) Update(diagnose *Diagnose) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", diagnose)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDiagnoseRepoMockRecorder) Update(diagnose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDiagnoseRepo)(nil).Update), diagnose)
}
