// Code generated by MockGen. DO NOT EDIT.
// Source: service/doctors/doctor_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/doctors/doctor_repo.go -destination=service/doctors/mock_repo.go -package=doctors
//

// Package doctors is a generated GoMock package.
package doctors

import (
	doctor "Dedenruslan19/med-project/repository/doctor"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDoctorRepo is a mock of DoctorRepo interface.
type MockDoctorRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDoctorRepoMockRecorder
	isgomock struct{}
}

// MockDoctorRepoMockRecorder is the mock recorder for MockDoctorRepo.
type MockDoctorRepoMockRecorder struct {
	mock *MockDoctorRepo
}

// NewMockDoctorRepo creates a new mock instance.
func NewMockDoctorRepo(ctrl *gomock.Controller) *MockDoctorRepo {
	mock := &MockDoctorRepo{ctrl: ctrl}
	mock.recorder = &MockDoctorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoctorRepo) EXPECT() *MockDoctorRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDoctorRepo) Create(arg0 *doctor.Doctor) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDoctorRepoMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDoctorRepo)(nil).Create), arg0)
}

// GetAll mocks base method.
func (m *MockDoctorRepo) GetAll() ([]doctor.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]doctor.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDoctorRepoMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDoctorRepo)(nil).GetAll))
}

// GetByEmail mocks base method.
func (m *MockDoctorRepo) GetByEmail(email string) (*doctor.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*doctor.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockDoctorRepoMockRecorder) GetByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockDoctorRepo)(nil).GetByEmail), email)
}

// GetByID mocks base method.
func (m *MockDoctorRepo) GetByID(id int64) (*doctor.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*doctor.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDoctorRepoMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDoctorRepo)(nil).GetByID), id)
}
