// Code generated by MockGen. DO NOT EDIT.
// Source: service/exercises/exercise_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/exercises/exercise_repo.go -destination=service/exercises/mock_repo.go -package=exercises
//

// Package exercises is a generated GoMock package.
package exercises

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExerciseRepo is a mock of ExerciseRepo interface.
type MockExerciseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseRepoMockRecorder
	isgomock struct{}
}

// MockExerciseRepoMockRecorder is the mock recorder for MockExerciseRepo.
type MockExerciseRepoMockRecorder struct {
	mock *MockExerciseRepo
}

// NewMockExerciseRepo creates a new mock instance.
func NewMockExerciseRepo(ctrl *gomock.Controller) *MockExerciseRepo {
	mock := &MockExerciseRepo{ctrl: ctrl}
	mock.recorder = &MockExerciseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExerciseRepo) EXPECT() *MockExerciseRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExerciseRepo) Create(exercise *Exercise) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", exercise)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExerciseRepoMockRecorder) Create(exercise any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExerciseRepo)(nil).Create), exercise)
}

// Delete mocks base method.
func (m *MockExerciseRepo) Delete(exerciseID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", exerciseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExerciseRepoMockRecorder) Delete(exerciseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExerciseRepo)(nil).Delete), exerciseID)
}

// GetByID mocks base method.
func (m *MockExerciseRepo) GetByID(exerciseID int64) (*Exercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", exerciseID)
	ret0, _ := ret[0].(*Exercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockExerciseRepoMockRecorder) GetByID(exerciseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockExerciseRepo)(nil).GetByID), exerciseID)
}

// GetByWorkoutID mocks base method.
func (m *MockExerciseRepo) GetByWorkoutID(workoutID int64) ([]Exercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWorkoutID", workoutID)
	ret0, _ := ret[0].([]Exercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWorkoutID indicates an expected call of GetByWorkoutID.
func (mr *MockExerciseRepoMockRecorder) GetByWorkoutID(workoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWorkoutID", reflect.TypeOf((*MockExerciseRepo)(nil).GetByWorkoutID), workoutID)
}

// Update mocks base method.
func (m *MockExerciseRepo) Update(exercise *Exercise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", exercise)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExerciseRepoMockRecorder) Update(exercise any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExerciseRepo)(nil).Update), exercise)
}
