// Code generated by MockGen. DO NOT EDIT.
// Source: service/billings/billing_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/billings/billing_repo.go -destination=service/billings/mock_repo.go -package=billings
//

// Package billings is a generated GoMock package.
package billings

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBillingRepo is a mock of BillingRepo interface.
type MockBillingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBillingRepoMockRecorder
	isgomock struct{}
}

// MockBillingRepoMockRecorder is the mock recorder for MockBillingRepo.
type MockBillingRepoMockRecorder struct {
	mock *MockBillingRepo
}

// NewMockBillingRepo creates a new mock instance.
func NewMockBillingRepo(ctrl *gomock.Controller) *MockBillingRepo {
	mock := &MockBillingRepo{ctrl: ctrl}
	mock.recorder = &MockBillingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingRepo) EXPECT() *MockBillingRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBillingRepo) Create(billing *Billing) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", billing)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBillingRepoMockRecorder) Create(billing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBillingRepo)(nil).Create), billing)
}

// GetByAppointmentID mocks base method.
func (m *MockBillingRepo) GetByAppointmentID(appointmentID int64) (*Billing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAppointmentID", appointmentID)
	ret0, _ := ret[0].(*Billing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAppointmentID indicates an expected call of GetByAppointmentID.
func (mr *MockBillingRepoMockRecorder) GetByAppointmentID(appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAppointmentID", reflect.TypeOf((*MockBillingRepo)(nil).GetByAppointmentID), appointmentID)
}

// GetByID mocks base method.
func (m *MockBillingRepo) GetByID(id int64) (*Billing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*Billing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBillingRepoMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBillingRepo)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockBillingRepo) Update(billing *Billing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", billing)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBillingRepoMockRecorder) Update(billing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBillingRepo)(nil).Update), billing)
}
