// Code generated by MockGen. DO NOT EDIT.
// Source: service/workouts/workout_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/workouts/workout_repo.go -destination=service/workouts/mock_repo.go -package=workouts
//

// Package workouts is a generated GoMock package.
package workouts

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkoutRepo is a mock of WorkoutRepo interface.
type MockWorkoutRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkoutRepoMockRecorder
	isgomock struct{}
}

// MockWorkoutRepoMockRecorder is the mock recorder for MockWorkoutRepo.
type MockWorkoutRepoMockRecorder struct {
	mock *MockWorkoutRepo
}

// NewMockWorkoutRepo creates a new mock instance.
func NewMockWorkoutRepo(ctrl *gomock.Controller) *MockWorkoutRepo {
	mock := &MockWorkoutRepo{ctrl: ctrl}
	mock.recorder = &MockWorkoutRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkoutRepo) EXPECT() *MockWorkoutRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkoutRepo) Create(workout *Workout) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", workout)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkoutRepoMockRecorder) Create(workout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkoutRepo)(nil).Create), workout)
}

// CreateExercise mocks base method.
func (m *MockWorkoutRepo) CreateExercise(exercise *Exercise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExercise", exercise)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExercise indicates an expected call of CreateExercise.
func (mr *MockWorkoutRepoMockRecorder) CreateExercise(exercise any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExercise", reflect.TypeOf((*MockWorkoutRepo)(nil).CreateExercise), exercise)
}

// Delete mocks base method.
func (m *MockWorkoutRepo) Delete(workoutID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", workoutID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkoutRepoMockRecorder) Delete(workoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkoutRepo)(nil).Delete), workoutID)
}

// GetAll mocks base method.
func (m *MockWorkoutRepo) GetAll() ([]Workout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]Workout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWorkoutRepoMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWorkoutRepo)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockWorkoutRepo) GetByID(workoutID int64) (*Workout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", workoutID)
	ret0, _ := ret[0].(*Workout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWorkoutRepoMockRecorder) GetByID(workoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWorkoutRepo)(nil).GetByID), workoutID)
}

// GetOwnerID mocks base method.
func (m *MockWorkoutRepo) GetOwnerID(workoutID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerID", workoutID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerID indicates an expected call of GetOwnerID.
func (mr *MockWorkoutRepoMockRecorder) GetOwnerID(workoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerID", reflect.TypeOf((*MockWorkoutRepo)(nil).GetOwnerID), workoutID)
}

// Update mocks base method.
func (m *MockWorkoutRepo) Update(workout *Workout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", workout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWorkoutRepoMockRecorder) Update(workout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkoutRepo)(nil).Update), workout)
}
