// Code generated by MockGen. DO NOT EDIT.
// Source: service/invoices/invoice_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/invoices/invoice_repo.go -destination=service/invoices/mock_repo.go -package=invoices
//

// Package invoices is a generated GoMock package.
package invoices

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceRepo is a mock of InvoiceRepo interface.
type MockInvoiceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepoMockRecorder
	isgomock struct{}
}

// MockInvoiceRepoMockRecorder is the mock recorder for MockInvoiceRepo.
type MockInvoiceRepoMockRecorder struct {
	mock *MockInvoiceRepo
}

// NewMockInvoiceRepo creates a new mock instance.
func NewMockInvoiceRepo(ctrl *gomock.Controller) *MockInvoiceRepo {
	mock := &MockInvoiceRepo{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepo) EXPECT() *MockInvoiceRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoiceRepo) Create(invoice *Invoice) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", invoice)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceRepoMockRecorder) Create(invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceRepo)(nil).Create), invoice)
}

// GetByBillingID mocks base method.
func (m *MockInvoiceRepo) GetByBillingID(billingID int64) (*Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBillingID", billingID)
	ret0, _ := ret[0].(*Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBillingID indicates an expected call of GetByBillingID.
func (mr *MockInvoiceRepoMockRecorder) GetByBillingID(billingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBillingID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetByBillingID), billingID)
}

// GetByID mocks base method.
func (m *MockInvoiceRepo) GetByID(id int64) (*Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInvoiceRepoMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetByID), id)
}

// UpdateSentAt mocks base method.
func (m *MockInvoiceRepo) UpdateSentAt(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSentAt", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSentAt indicates an expected call of UpdateSentAt.
func (mr *MockInvoiceRepoMockRecorder) UpdateSentAt(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSentAt", reflect.TypeOf((*MockInvoiceRepo)(nil).UpdateSentAt), id)
}
