// Code generated by MockGen. DO NOT EDIT.
// Source: service/logs/log_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/logs/log_repo.go -destination=service/logs/mock_repo.go -package=logs
//

// Package logs is a generated GoMock package.
package logs

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogRepo is a mock of LogRepo interface.
type MockLogRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLogRepoMockRecorder
	isgomock struct{}
}

// MockLogRepoMockRecorder is the mock recorder for MockLogRepo.
type MockLogRepoMockRecorder struct {
	mock *MockLogRepo
}

// NewMockLogRepo creates a new mock instance.
func NewMockLogRepo(ctrl *gomock.Controller) *MockLogRepo {
	mock := &MockLogRepo{ctrl: ctrl}
	mock.recorder = &MockLogRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRepo) EXPECT() *MockLogRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLogRepo) Create(log *ExerciseLog) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLogRepoMockRecorder) Create(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLogRepo)(nil).Create), log)
}

// Delete mocks base method.
func (m *MockLogRepo) Delete(logID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", logID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLogRepoMockRecorder) Delete(logID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLogRepo)(nil).Delete), logID)
}

// GetAll mocks base method.
func (m *MockLogRepo) GetAll() ([]ExerciseLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]ExerciseLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLogRepoMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLogRepo)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockLogRepo) GetByID(logID int64) (*ExerciseLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", logID)
	ret0, _ := ret[0].(*ExerciseLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLogRepoMockRecorder) GetByID(logID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLogRepo)(nil).GetByID), logID)
}

// GetByUserID mocks base method.
func (m *MockLogRepo) GetByUserID(userID int64) ([]ExerciseLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]ExerciseLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockLogRepoMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockLogRepo)(nil).GetByUserID), userID)
}
