// Code generated by MockGen. DO NOT EDIT.
// Source: service/appointments/appointment_repo.go
//
// Generated by this command:
//
//	mockgen -source=service/appointments/appointment_repo.go -destination=service/appointments/mock_repo.go -package=appointments
//

// Package appointments is a generated GoMock package.
package appointments

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAppointmentRepo is a mock of AppointmentRepo interface.
type MockAppointmentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentRepoMockRecorder
	isgomock struct{}
}

// MockAppointmentRepoMockRecorder is the mock recorder for MockAppointmentRepo.
type MockAppointmentRepoMockRecorder struct {
	mock *MockAppointmentRepo
}

// NewMockAppointmentRepo creates a new mock instance.
func NewMockAppointmentRepo(ctrl *gomock.Controller) *MockAppointmentRepo {
	mock := &MockAppointmentRepo{ctrl: ctrl}
	mock.recorder = &MockAppointmentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentRepo) EXPECT() *MockAppointmentRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppointmentRepo) Create(appointment *Appointment) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", appointment)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAppointmentRepoMockRecorder) Create(appointment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppointmentRepo)(nil).Create), appointment)
}

// GetByID mocks base method.
func (m *MockAppointmentRepo) GetByID(id int64) (*Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAppointmentRepoMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAppointmentRepo)(nil).GetByID), id)
}

// GetByUserID mocks base method.
func (m *MockAppointmentRepo) GetByUserID(userID int64) ([]Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockAppointmentRepoMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockAppointmentRepo)(nil).GetByUserID), userID)
}

// IsDoctorAvailable mocks base method.
func (m *MockAppointmentRepo) IsDoctorAvailable(doctorID int64, appointmentDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDoctorAvailable", doctorID, appointmentDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDoctorAvailable indicates an expected call of IsDoctorAvailable.
func (mr *MockAppointmentRepoMockRecorder) IsDoctorAvailable(doctorID, appointmentDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDoctorAvailable", reflect.TypeOf((*MockAppointmentRepo)(nil).IsDoctorAvailable), doctorID, appointmentDate)
}

// UpdateStatus mocks base method.
func (m *MockAppointmentRepo) UpdateStatus(id int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAppointmentRepoMockRecorder) UpdateStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAppointmentRepo)(nil).UpdateStatus), id, status)
}
